- *Author* : **Ibrahima Sy** 

- *Email*: syibrahima31@gmai.com
- *github* : [Cliquez](https://github.com/syibrahima31)

## OUTLINE
--------------------------------------------------------------------------------------------------------------------------
1. Numpy introduction
2. Array basics 
3. Array vs list
4. Dot Product 
5. Speed Test array vs list 
6. Multidimensional arrays 
7. Array indexing / slicing / boolean indexing 
8. Reshape 
9. Concatenation 

10. Broadcasting 
11. (Data Science) Functions and Axis 
12. Datatypes 
13. Copying
14. Generating arrays 
15. Random numbers 
16. Linear Algebra(np.linalg)

    -Eienvalues 
    
17. Load Data form csv 


## **NUMPY** 
-------------------------------------------------------------

**NumPy** est une bibliothèque pour langage de programmation Python, destinée à manipuler des *matrices* ou **tableaux     multidimensionnels** ainsi que des fonctions mathématiques   opérant sur ces tableaux.

Plus précisément, cette bibliothèque logicielle libre et open source fournit de multiples fonctions permettant notamment de créer directement un tableau depuis un fichier ou au contraire de sauvegarder un tableau dans un fichier, et manipuler des vecteurs, matrices et polynômes.

NumPy est la base de nombreuses bibliothéques: 

- **Data Science** , **Machine Leaning **, **Deep Learning**
- **scikit-learn** , **matpltolib**, **pandas**


**Numpy** a été ecrit en language **C**

In [20]:
#Importation de la librairie numpy 
import numpy as np 

#regrader la version de numpy
print(np.__version__)


1.19.2


### BASICS IN NUMPY 

In [275]:
# creation d'un tableau numpy 
a = np.array([1,2,4])

# shape : retourne la taille du tableau 
a.shape 

# ndim : retourne : la dimensio de du tableau 
a.ndim 

# size : retourne le nombre d'éléments dans le tableau 
a.size 

# a.dtype : retourne le type des elements dans le tableau 

# a.itemsize 
a.itemsize 

# acces au premier elements 
a[0]

# changer un elements
a[0] = 10 

#multiplication de deux tableau 

b = a* np.array([1,2,0])


### ARRAY vs LIST 

In [291]:
# creation d'une liste 
L = [1,2,3]
print(L)

# creation d'un tableau numpy 
A = np.array([1,2,3])
print(A)

# diffence 
L + 2       # don't works 
L * 2       # pas le meme sens 
L + [4]     # meme role que append a peut prés


# tableau numpy 

A + 2       #  il fait ce qu'on appelle le broadcasting
A  * 2      #  meme chose 
A.append(3) # pas possible de rallonger le tableau une fois crees cést fini

A + np.array([2]) # meme idée que le broadcasting 


# Notion de vectorisation 
np.sqrt(L)  # retourne un tableau de meme taille 

### DOT PRODUCT 

In [90]:
# creation de de deux listes 
L_1 = [1,2,3]
L_2 = [2,4,5]

#creation de deux vecteurs numpy 
A_1 = np.array([1,2,3])
A_2  = np.array([2,4,5])

In [73]:
somme = 0
for i in range(3):
    somme = somme + L_1[i]*L_2[i]
    
print(somme)
    
    

25


### SPEED TEST ARRAY VS LIST 

In [79]:
import time 

In [91]:
def dot_list():
    somme = 0
    for i in range(3):
        somme = somme + L_1[i]*L_2[i]
    return somme

def dot_array():
    return A_1.dot(A_2)


In [95]:
T = 1000

# mesure le temps avec les listes 
begin_1 = time.time()

for i in range(T):
    dot_list()

end_1  = time.time()

t_1 = end_1 - begin_1
# on mesure le temps avec le tableau numpy 

begin_2 = time.time()
for i in range(T):
    dot_array()
end_2 = time.time()

t_2 = end_2 - begin_2

In [96]:
t_1 , t_2

(0.002993345260620117, 0.004418373107910156)

In [97]:
print(f"temps avec les listes :{t_1:.6f}")
print(f"temps avec les tableaux numpy: { t_2 : .6f}" )
print(f"On compare le ratio {t_1 / t_2 }")

temps avec les listes :0.002993
temps avec les tableaux numpy:  0.004418
On compare le ratio 0.6774767968918627


### MULTIDIMENSIONNAL ARRAYS 

In [289]:
# tableau en 1 D 
a = np.array([1,2,3])
print(a.shape)

# tableau a  2 D 
b= np.array([[1,2,3], [4,3,2]])
print(b.shape)

b[0][0]  # on peut acceder comme ca au prrmier elements 
b[0,0]   # c'est ce qui est conseillé 

# transpose the matrix 
b.T 

#inverse de la matrice 
np.linalg.inv(b)  

# diagonal matrice 
np.diag(b)

In [112]:
b= np.array([[1,2], [4,3]])

np.linalg.inv(b)

array([[-0.6,  0.4],
       [ 0.8, -0.2]])

### ARRAY INDEXING /SLICING / BOOLEAN INDEXING  

In [114]:
a = np.array([[1,2,3,4], [3,4, 5,6]])

# indexation 1 element 
a[0, 0 ]

# a[0] acceder a la premiere ligne 
a[0]

# a[1] acceder la second ligne 
a[1]

# a[0:2, 1:2]  slicing 
a[0:2, 1:2]  

array([[2],
       [4]])

In [137]:
# bolean indexing 
np.random.seed(120)

a = np.random.randint(1,10, size=(4,4))
print(a)

# on recupere les valeurs supérieiur á 5 

index_bool = a > 5 
index_bool 

print(a[index_bool])  # on recupere les vaeurs mais dans un tableau a 1 D


# np.where permet de regeler cela
np.where(a > 5, a , 0)

[[8 1 9 5]
 [2 8 2 4]
 [9 5 7 8]
 [2 5 6 8]]


In [132]:
# fancy indexing 
a = np.array([10,119,30, 41, 50 , 61])

index = np.argwhere(a%2 == 0 ).ravel()

a[index ]

array([10, 30, 50])

### RESHAPE ARRAY 

In [292]:
a = np.arange(10)

# la taille 
print(a.shape)

# # reshape 
a.reshape(2,5)

# # use newaxis 
a[:, np.newaxis]


(1, 10)

### CONCATENATION 

In [161]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])

# use np.concatenate 
np.concatenate([a,b], axis = None ) # utiliser axis et penser a faire du reshaping 

# use hstack and vstack

# np.vstack([a,b])
a, b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6]]))

In [168]:
np.hstack((a,b.reshape(-1,1)))


array([[1, 2, 5],
       [3, 4, 6]])

###  BROADCASTING 

In [173]:
x = np.array([[1,2,3],[4,5,6], [1,2,3], [4,5,6]])
a = np.array([1,0,1])

array([[2, 2, 4],
       [5, 5, 7],
       [2, 2, 4],
       [5, 5, 7]])

### FUNCTIONS AXIS 

In [178]:
np.random.seed(30)

a = np.random.randint(1,10, size =(4,4) )

# sum avec la precision de axis 

a.sum()

a.sum(axis= 0)
a.sum(axis = 1)

a.var()

4.33984375

In [179]:
a 

array([[6, 6, 5, 8],
       [3, 6, 2, 4],
       [8, 8, 2, 2],
       [4, 3, 3, 5]])

In [186]:
# np.sum(a)
a.mean(axis = 1)

array([6.25, 3.75, 5.  , 3.75])

### DATATYPES 

In [194]:
x = np.array([1,2,3.0], dtype = np.float64)

print(x)

print(x.dtype)

x.astype(np.int64)  # ou bien lors de la creation avec array 

[1. 2. 3.]
float64


array([1, 2, 3], dtype=int64)

###  COPYING 

In [204]:
a = np.array([1,2,4])

a

b = a.copy()

a[0] = 1000

b

array([1, 2, 4])

### GENERATING ARRAYS 

In [242]:
# np.zeros()

np.zeros(10) # vecteur ou matrice remplie de 0

np.ones((2,4)) #  vecteur ou matrice remplie de 1 

np.full((2,2), 4) # tu specifie la valeur de remplissage

np.eye(2)    # creationde la mmatrice identite 

np.arange(10) # equivalent de range

np.linspace(-10,10, 10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [219]:
np.full(shape =(4,4),fill_value=3)

a[a== 2] = 100


array([1000,  100,    4])

### RANDOM NUMBERS 

In [225]:
a = np.random.randn(10)

b = np.random.random( 100)  # gaussian distribution 

c = np.random.randint(1,5)

a = np.random.choice(5, size = 10)
print(a)

[3 1 1 4 2 1 1 1 4 2]


### LINEAR ALGEBRA (np.linalg)

def : Soit $A$ une matrice carré de type $n \times n $ alors un vecteur propre $A$ est un vecteur $\vec{u}$ qui satifait les conditions suivants :

$$A\vec{u} = \lambda \vec{u}$$

In [266]:
a = np.array([[1,2], [3,4]])

eigenvalues, eigenvectors = np.linalg.eig(a)
print(eigenvalues)
print(eigenvectors) # columns vectors 

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [272]:
eigenvalues * eigenvectors 

array([[ 0.30697009, -2.23472698],
       [-0.21062466, -4.88542751]])

In [273]:
a.dot(eigenvectors)

array([[ 0.30697009, -2.23472698],
       [-0.21062466, -4.88542751]])

### LOAD DATA  FROM  csv 

In [19]:
# use genformtxt or loadtxthttp://localhost:8888/notebooks/Desktop/Master%20Data%20Science%20et%20IA/Data%20Analysis/Chapitre%201/Numpy%20tutorial%20.ipynb#
import numpy as np 

# # np.genfromtxt()

# np.loadtxt()

In [228]:
 wine = np.genfromtxt("wine.csv", delimiter=",",skip_header= 1)

In [230]:
wine.shape 

(178, 14)